config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :strains
  resources :wines
  # root "strains#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/strain.rb
class Strain < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    # Relacionamos la tabla con la intermedia 
    has_many :wine_strains
    has_many :wines, through: :wine_strains
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    # Relacionamos la tabla con la intermedia 
    has_many :wine_strains
    has_many :strains, through: :wine_strains
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
    belongs_to :wine
    belongs_to :strain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private
  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all.order("name ASC")
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy

    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name, :status)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, { strain_ids: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisCepas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">

  </head>

  <body class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/strains/_form.html.erb
<%= form_with(model: strain) do |form| %>
  <% if strain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
        <% strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/_strain.html.erb
<div id="<%= dom_id strain %>">
  <p>
    <strong>Name:</strong>
    <%= strain.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= strain.status %>
  </p>

</div>

app/views/strains/edit.html.erb
<h1>Editing strain</h1>

<%= render "form", strain: @strain %>

<br>

<div>
  <%= link_to "Show this strain", @strain %> |
  <%= link_to "Back to strains", strains_path %>
</div>

app/views/strains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Strains</h1>

<div id="strains">
  <% @strains.each do |strain| %>
    <%= render strain %>
    <p>
      <%= link_to "Show this strain", strain %>
    </p>
  <% end %>
</div>

<%= link_to "New strain", new_strain_path %>

app/views/strains/new.html.erb
<h1>New strain</h1>

<%= render "form", strain: @strain %>

<br>

<div>
  <%= link_to "Back to strains", strains_path %>
</div>

app/views/strains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @strain %>

<div>
  <%= link_to "Edit this strain", edit_strain_path(@strain) %> |
  <%= link_to "Back to strains", strains_path %>

  <%= button_to "Destroy this strain", @strain, method: :delete %>
</div>

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t('common.name'), style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <%= form.label :strains, style: "display: block" %>
    <%= form.collection_check_boxes(:strain_ids, 
      Strain.all,
      :id, 
      :name) do |b| %>
      <%= b.label class:"label-checkbox" do%>
      <%=b.check_box + b.text%>
    <%end%>
  <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine.html.erb
<div id="<%= dom_id wine %>">
  <p>
    <strong><%= t('common.name') %></strong>
    <%= wine.name %>
  </p>

</div>

app/views/wines/edit.html.erb
<h2><%= t('.title')%></h2>

<%= render "form", wine: @wine %>

<br>

<div>
  <%= link_to t('show.wine'), @wine %> |
  <%= link_to t('back.wines'), wines_path %>
</div>

app/views/wines/index.html.erb
<p style="color: green"><%= notice %></p>

<h2><%= t('common.title')%></h2>

<div id="wines">
  <% @wines.each do |wine| %>
    <%= render wine %>
    <p>
      <%= link_to t('show.wine'), wine %>
    </p>
  <% end %>
</div>

<%= link_to t('new.wine'), new_wine_path %>

app/views/wines/new.html.erb
<h2><%= t('.title')%></h2>


<%= render "form", wine: @wine %>

<br>

<div>
  <%= link_to t('back.wines'), wines_path %> 
</div>

app/views/wines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wine %>

<div>
  <%= link_to t('edit.wine'), edit_wine_path(@wine) %> |
  <%= link_to t('back.wines'), wines_path %>

  <%= button_to t('destroy.wine'), @wine, method: :delete %>
</div>